docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
site_name: oneplace-event
site_description: "onePlace Livechat"
repo_url: 'https://github.com/OnePlc/PLC_X_Livechat'
theme: bootstrap4
extra:
  project: onePlc